// flow-typed signature: 2e0416bc044021a642804e3e1effb60c
// flow-typed version: <<STUB>>/@storybook/addon-notes_v^5.3.13/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-notes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-notes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-notes/dist/formatter' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/giphy' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/public_api' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/register-panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-notes/dist/formatter.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/formatter'>;
}
declare module '@storybook/addon-notes/dist/giphy.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/giphy'>;
}
declare module '@storybook/addon-notes/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist'>;
}
declare module '@storybook/addon-notes/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist'>;
}
declare module '@storybook/addon-notes/dist/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/Panel'>;
}
declare module '@storybook/addon-notes/dist/public_api.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/public_api'>;
}
declare module '@storybook/addon-notes/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/register'>;
}
declare module '@storybook/addon-notes/dist/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/shared'>;
}
declare module '@storybook/addon-notes/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/typings.d'>;
}
declare module '@storybook/addon-notes/register-panel.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/register-panel'>;
}
declare module '@storybook/addon-notes/register.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/register'>;
}
