// flow-typed signature: d6ee2cd870ac6d34c3ae4f1f208cecc7
// flow-typed version: <<STUB>>/react-scroll-to-bottom_v^1.3.2/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-to-bottom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-to-bottom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll-to-bottom/lib/BasicScrollToBottom' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/debounce' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/EventSpy' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/ScrollToBottom/AutoHideFollowButton' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/ScrollToBottom/Composer' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/ScrollToBottom/FunctionContext' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/ScrollToBottom/InternalContext' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/ScrollToBottom/Panel' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/ScrollToBottom/StateContext' {
  declare module.exports: any;
}

declare module 'react-scroll-to-bottom/lib/SpineTo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll-to-bottom/lib/BasicScrollToBottom.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/BasicScrollToBottom'>;
}
declare module 'react-scroll-to-bottom/lib/debounce.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/debounce'>;
}
declare module 'react-scroll-to-bottom/lib/EventSpy.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/EventSpy'>;
}
declare module 'react-scroll-to-bottom/lib/index' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib'>;
}
declare module 'react-scroll-to-bottom/lib/index.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib'>;
}
declare module 'react-scroll-to-bottom/lib/ScrollToBottom/AutoHideFollowButton.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/ScrollToBottom/AutoHideFollowButton'>;
}
declare module 'react-scroll-to-bottom/lib/ScrollToBottom/Composer.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/ScrollToBottom/Composer'>;
}
declare module 'react-scroll-to-bottom/lib/ScrollToBottom/FunctionContext.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/ScrollToBottom/FunctionContext'>;
}
declare module 'react-scroll-to-bottom/lib/ScrollToBottom/InternalContext.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/ScrollToBottom/InternalContext'>;
}
declare module 'react-scroll-to-bottom/lib/ScrollToBottom/Panel.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/ScrollToBottom/Panel'>;
}
declare module 'react-scroll-to-bottom/lib/ScrollToBottom/StateContext.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/ScrollToBottom/StateContext'>;
}
declare module 'react-scroll-to-bottom/lib/SpineTo.js' {
  declare module.exports: $Exports<'react-scroll-to-bottom/lib/SpineTo'>;
}
