// flow-typed signature: fa10263890fe0a8f6b291b11dfcff169
// flow-typed version: <<STUB>>/storybook-addon-material-ui_v^0.9.0-alpha.21/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-material-ui/dist/adk/ChannelHOC' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/adk/ChannelStore' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/adk/decorator' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/adk/panel' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/adk/WithChannel' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/AddonPanel' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/ThemePropBlock' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/ThemePropItem' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/ThemeSideBar' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/config' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/containers/MuiTheme' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/containers/PanelContainer' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SclAvatar' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SclToggle' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SvgButton' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SvgIcon' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/muiTheme' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/UI/AddonPanel' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/UI/FullTheme' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/UI/MuiDecorator' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/UI/Overridings' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/UI/Palette' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/Utils' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/Utils/svg_package' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/Utils/ui_package' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/Utils/uiTheme' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-material-ui/dist/adk/ChannelHOC.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/adk/ChannelHOC'>;
}
declare module 'storybook-addon-material-ui/dist/adk/ChannelStore.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/adk/ChannelStore'>;
}
declare module 'storybook-addon-material-ui/dist/adk/decorator.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/adk/decorator'>;
}
declare module 'storybook-addon-material-ui/dist/adk/panel.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/adk/panel'>;
}
declare module 'storybook-addon-material-ui/dist/adk/WithChannel.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/adk/WithChannel'>;
}
declare module 'storybook-addon-material-ui/dist/components/AddonPanel.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/AddonPanel'>;
}
declare module 'storybook-addon-material-ui/dist/components/ThemePropBlock.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemePropBlock'>;
}
declare module 'storybook-addon-material-ui/dist/components/ThemePropItem.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemePropItem'>;
}
declare module 'storybook-addon-material-ui/dist/components/ThemeSideBar.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemeSideBar'>;
}
declare module 'storybook-addon-material-ui/dist/config.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/config'>;
}
declare module 'storybook-addon-material-ui/dist/containers/MuiTheme.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/containers/MuiTheme'>;
}
declare module 'storybook-addon-material-ui/dist/containers/PanelContainer.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/containers/PanelContainer'>;
}
declare module 'storybook-addon-material-ui/dist/index' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist'>;
}
declare module 'storybook-addon-material-ui/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SclAvatar.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SclAvatar'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SclToggle.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SclToggle'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SvgButton.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SvgButton'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SvgIcon.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SvgIcon'>;
}
declare module 'storybook-addon-material-ui/dist/muiTheme.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/muiTheme'>;
}
declare module 'storybook-addon-material-ui/dist/register.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/register'>;
}
declare module 'storybook-addon-material-ui/dist/UI/AddonPanel.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/UI/AddonPanel'>;
}
declare module 'storybook-addon-material-ui/dist/UI/FullTheme.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/UI/FullTheme'>;
}
declare module 'storybook-addon-material-ui/dist/UI/MuiDecorator.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/UI/MuiDecorator'>;
}
declare module 'storybook-addon-material-ui/dist/UI/Overridings.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/UI/Overridings'>;
}
declare module 'storybook-addon-material-ui/dist/UI/Palette.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/UI/Palette'>;
}
declare module 'storybook-addon-material-ui/dist/Utils/index' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/Utils'>;
}
declare module 'storybook-addon-material-ui/dist/Utils/index.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/Utils'>;
}
declare module 'storybook-addon-material-ui/dist/Utils/svg_package.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/Utils/svg_package'>;
}
declare module 'storybook-addon-material-ui/dist/Utils/ui_package.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/Utils/ui_package'>;
}
declare module 'storybook-addon-material-ui/dist/Utils/uiTheme.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/Utils/uiTheme'>;
}
declare module 'storybook-addon-material-ui/register.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/register'>;
}
