// flow-typed signature: fee44387f653049c9a6f9a41c5172b80
// flow-typed version: <<STUB>>/unirest_v^0.6.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unirest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unirest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unirest/tests/basic' {
  declare module.exports: any;
}

declare module 'unirest/tests/promises' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unirest/index' {
  declare module.exports: $Exports<'unirest'>;
}
declare module 'unirest/index.js' {
  declare module.exports: $Exports<'unirest'>;
}
declare module 'unirest/tests/basic.js' {
  declare module.exports: $Exports<'unirest/tests/basic'>;
}
declare module 'unirest/tests/promises.js' {
  declare module.exports: $Exports<'unirest/tests/promises'>;
}
